export const OPEN_NAV_DRAWER = "OPEN_NAV_DRAWER";
export const CLOSE_NAV_DRAWER = "CLOSE_NAV_DRAWER";
export const TYPING_MSG = "TYPING_MSG";
export const SENDING_MSG = "SENDING_MSG";
export const CLICK_CONTACT = "CLICK_CONTACT";
export const FORCE_RE_RENDER = "FORCE_RE_RENDER";
export const GET_ALL_CONTACTS_LIST_FROM_DB = "GET_ALL_CONTACTS_LIST_FROM_DB";
export const GET_CHAT_MESSAGES_HISTORY = "GET_CHAT_MESSAGES_HISTORY";
